// Flashcards, taken from the "key terms" lists in the book.
export const GLOSSARY = [
  ['Excel', 'Workbook', 'A file containing one or more worksheets.'], ['Excel', 'Range', 'A group of two or more adjacent cells, e.g. A1:A10.'],
  ['Excel', 'Function', 'A predefined formula that performs a specific calculation, e.g. SUM.'], ['Excel', 'Pivot table', 'A tool that summarizes and analyzes large data sets in a compact table.'],
  ['Excel', 'Conditional formatting', 'Formatting that is applied to cells automatically when they meet a condition.'], ['Excel', 'Data validation', 'A rule that restricts what can be typed into a cell.'],
  ['Excel', 'Power Pivot', 'A data-modelling add-in: relationships between tables, calculated columns and measures.'], ['Excel', 'XLOOKUP', 'Modern lookup: finds a value in one range and returns the match from another range.'],
  ['Excel', 'Goal Seek', 'What-if tool that finds the input needed to reach a target output.'], ['Excel', 'Sparkline', 'A tiny chart that lives inside a single cell.'],
  ['Power BI', 'Fact table', 'The central table of a star schema holding numeric, measurable facts.'], ['Power BI', 'Dimension table', 'Descriptive context (who, what, when, where) for the facts.'],
  ['Power BI', 'Measure', 'A calculation evaluated at query time, respecting the report’s filters.'], ['Power BI', 'Calculated column', 'A per-row formula stored in the table; it does not react to report filters.'],
  ['Power BI', 'Power Query', 'The ETL tool: connect, transform and load data. Every step is recorded.'], ['Power BI', 'Slicer', 'An on-canvas control that filters the report.'],
  ['Power BI', 'Star schema', 'One fact table surrounded by dimension tables joined 1:many.'], ['Power BI', 'Filter context', 'The set of filters in force when a DAX measure is evaluated.'],
  ['Power BI', 'Cardinality', 'How rows in two tables relate: 1:1, 1:many or many:many.'], ['Power BI', 'DAX', 'Data Analysis Expressions, the formula language of Power BI.'],
  ['SQL', 'Primary key', 'A column (or columns) that uniquely identifies each row.'], ['SQL', 'Foreign key', 'A column that references another table’s primary key.'],
  ['SQL', 'INNER JOIN', 'Returns only rows that have a match in both tables.'], ['SQL', 'LEFT JOIN', 'All rows from the left table plus matches from the right (NULLs where none).'],
  ['SQL', 'GROUP BY', 'Collapses rows into groups so aggregate functions can summarize each group.'], ['SQL', 'HAVING', 'Filters groups after aggregation (WHERE filters rows before).'],
  ['SQL', 'UNION vs UNION ALL', 'UNION removes duplicate rows; UNION ALL keeps them.'], ['SQL', 'View', 'A saved query that behaves like a virtual table.'],
  ['SQL', 'Subquery', 'A query nested inside another query.'], ['SQL', 'Normalization', 'Organizing tables to reduce redundancy: 1NF, 2NF, 3NF.'],
  ['SQL', 'NULL', 'The absence of a value. Test it with IS NULL, never = NULL.'], ['SQL', 'CASE', 'SQL’s conditional expression (the equivalent of IF/SWITCH).'],
  ['Python', 'List comprehension', 'A one-line way to build a list: [x**2 for x in nums if x > 0].'], ['Python', 'Tuple', 'An ordered, immutable collection.'],
  ['Python', 'Dictionary', 'Unordered key → value pairs.'], ['Python', 'Set', 'An unordered collection of unique items.'],
  ['Python', 'DataFrame', 'Pandas’ 2-D table: labelled rows and columns.'], ['Python', 'Series', 'Pandas’ 1-D labelled array; one DataFrame column.'],
  ['Python', 'Vectorization', 'Operating on whole arrays at once instead of looping element by element.'], ['Python', 'Broadcasting', 'NumPy’s rule for combining arrays of different shapes.'],
  ['Python', 'Regex', 'A pattern language for searching and replacing text (module re).'], ['Python', 'Exception', 'A runtime error you can catch with try / except.'],
  ['Data Science', 'EDA', 'Exploratory data analysis: understand the data with summaries and plots before modelling.'], ['Data Science', 'Feature engineering', 'Creating or transforming variables so a model learns better.'],
  ['Data Science', 'Supervised learning', 'Learning from labelled examples (regression, classification).'], ['Data Science', 'Unsupervised learning', 'Finding structure in unlabelled data (clustering, PCA).'],
  ['Data Science', 'Cross-validation', 'Evaluating a model on several train/test splits to check it generalizes.'], ['Data Science', 'Precision vs recall', 'Precision: of predicted positives, how many are right. Recall: of real positives, how many were found.'],
];
