// Regression test: the book's DAX examples must evaluate on the practice dataset.
import { createEngine } from '../src/lib/dax-engine.js';
import { DAX_TABLES, DAX_RELATIONS } from '../src/lib/dax-data.js';
const e = createEngine(DAX_TABLES(), DAX_RELATIONS);
let fail = 0;
const t = (name, text, check) => {
  const r = e.load(text);
  let got, err = r.errors[0];
  if (!err) { try { got = e.evaluate(r.measures[0]); } catch (x) { err = x.message; } }
  const ok = !err && (check === undefined || check(got));
  if (!ok) fail++;
  console.log(ok ? 'ok  ' : 'FAIL', name, err ? '→ ' + err : '→ ' + String(JSON.stringify(got)).slice(0, 60));
};
const num = v => typeof v === 'number' && isFinite(v);
t('SUM', 'Total Sales Amount = SUM(sales[sales_amount])', num);
t('SUMX+FILTER (customer)', 'TotalCustOrders = SUMX(FILTER(orders, orders[customer_id] = 1), orders[order_total])', v => v === 350);
t('SUMX north', 'Total Sales Region = SUMX(FILTER(sales, sales[region] = "North"), sales[sales_amount])', num);
t('SUMX year', 'X = SUMX(FILTER(orders, YEAR(orders[order_date]) = 2022), orders[order_total])', v => v === 1000);
t('COUNT', 'X = COUNT(Sales[SalesAmount])', v => v === 72);
t('COUNTA', 'X = COUNTA(Customers[City])', v => v === 8);
t('COUNTAX+SUMMARIZE', 'X = COUNTAX(SUMMARIZE(Sales, Sales[Category], "Total Revenue", SUM(Sales[SalesAmount])), [Total Revenue])', v => v === 3);
t('COUNTBLANK', 'X = COUNTBLANK(Sales[Price])', v => v === 0);
t('COUNTROWS filter', 'X = COUNTROWS(FILTER(Sales, Sales[Price] > 100))', num);
t('DISTINCTCOUNT', 'X = DISTINCTCOUNT(Sales[Product])', v => v <= 6);
t('MINX', 'X = MINX(Sales, [Price] * [Quantity])', num);
t('MAXX filter', 'X = MAXX(FILTER(Employees, Employees[Age] < 30), [Salary])', v => v === 64000);
t('AVERAGEX', 'X = AVERAGEX(Sales, [Price] / [Quantity])', num);
t('AVERAGEX filter', 'X = AVERAGEX(FILTER(Employees, Employees[Age] < 30), Employees[Salary])', v => Math.abs(v - 54666.666) < 1);
t('CALENDAR', 'Calendar = CALENDAR(DATE(2021,1,1), DATE(2021,12,31))\n\nX = COUNTROWS(Calendar)', v => v === 365);
t('DATEDIFF days', 'Days = DATEDIFF(DATE(2021, 1, 1), DATE(2021, 12, 31), DAY)', v => v === 364);
t('DATEDIFF years', 'Years = DATEDIFF(DATE(1980, 1, 1), DATE(2022, 1, 1), YEAR)', v => v === 42);
t('WEEKDAY column', 'Employees[Kind] = IF(WEEKDAY(Employees[HireDate]) <= 5, "Weekday", "Weekend")\n\nX = COUNTROWS(FILTER(Employees, Employees[Kind] = "Weekday"))', num);
t('Overdue', 'Tasks[Status] = IF(Tasks[due_date] < TODAY(), "Overdue", "Not Overdue")\n\nX = COUNTROWS(FILTER(Tasks, Tasks[Status] = "Overdue"))', v => v === 2);
t('FILTER west', 'SalesAmount = CALCULATE(SUM(Sales[SalesAmount]), FILTER(Sales, Sales[Region] = "West"))', num);
t('AvgAge female', 'AvgAge = CALCULATE(AVERAGE(Customers[Age]), FILTER(Customers, Customers[Gender] = "Female"))', v => Math.abs(v - 36.75) < 0.01);
t('EARLIER max', 'MaxPrice = MAXX(DISTINCT(Products[Category]), CALCULATE(MAX(Products[Price]), FILTER(Products, Products[Category] = EARLIER(Products[Category]))))', v => v === 850);
t('FILTER && MONTH', 'TotalSales = CALCULATE(SUM(Sales[SalesAmount]), FILTER(Sales, Sales[Region] = "West" && MONTH(Sales[Month]) = 1))', undefined);
t('CALCULATE state', 'Total Sales California = CALCULATE(SUM(Sales[Sales Amount]), Sales[State] = "California")', num);
t('CALCULATE period', 'Q1 = CALCULATE(SUM(Sales[Sales Amount]), FILTER(Sales, Sales[Date] >= DATE(2022,1,1) && Sales[Date] <= DATE(2022,3,31)))', num);
t('ALL', 'Total Sales := CALCULATE(SUM(Sales[Sales Amount]), ALL(Sales[State]))', num);
t('ALL multi', 'Total Sales = CALCULATE(SUM(Sales[Sales Amount]), ALL(Sales[State], Sales[Product]))', num);
t('ALLEXCEPT', 'Total Sales = CALCULATE(SUM(Sales[Sales Amount]), ALLEXCEPT(Sales, Sales[State], Sales[Product]))', num);
t('ALLSELECTED', 'Total Sales All Categories = CALCULATE(SUM(Sales[SalesAmount]), ALLSELECTED(Sales[Category], Sales[Subcategory]))', num);
t('% of total', '% of Total Sales = DIVIDE(SUM(Sales[SalesAmount]), CALCULATE(SUM(Sales[SalesAmount]), ALLSELECTED()))', v => v === 1);
t('KEEPFILTERS', '=CALCULATE(AVERAGE(Products[Price]), KEEPFILTERS(Sales[Year] = YEAR(TODAY())))', undefined);
t('LOOKUPVALUE', '= LOOKUPVALUE(Products[Product Name], Products[Product ID], "P001", "Unknown")', v => v === 'Trail Bike');
t('LOOKUPVALUE default', '=LOOKUPVALUE(Sales[Sales Amount], Sales[Date], TODAY(), 0)', v => v === 0);
t('IF blank', 'MyMeasure = IF(COUNTROWS(Sales) > 0, AVERAGE(Sales[SalesAmount]), BLANK())', num);
t('IF calc column', 'Sales[SalesCategory] = IF(Sales[SalesAmount] > 1000, "High", "Low")\n\nX = COUNTROWS(FILTER(Sales, Sales[SalesCategory] = "High"))', num);
t('SWITCH', 'Employees[Rate] = SWITCH(Employees[Department], "Sales", 0.1, "Finance", 0.2, "IT", 0.3, 0.05)\n\nX = SUMX(Employees, Employees[Salary] * Employees[Rate])', num);
t('SWITCH TRUE', 'Customers[AgeGroup] = SWITCH(TRUE(), Customers[Age] < 18, "Under 18", Customers[Age] < 30, "18-29", Customers[Age] < 50, "30-49", Customers[Age] >= 50, "50 or older")\n\nX = COUNTROWS(FILTER(Customers, Customers[AgeGroup] = "50 or older"))', v => v === 2);
t('Growth VAR', 'G = VAR Prev = CALCULATE(SUM(Sales[SalesAmount]), Sales[Year] = 2021)\nVAR Cur = CALCULATE(SUM(Sales[SalesAmount]), Sales[Year] = 2022)\nRETURN DIVIDE(Cur - Prev, Prev)', num);
process.exit(fail ? 1 : 0);
